### ISSUE TITLE
IL 2022 já disponível

### ISSUE THREAD

**Issue by marado** [Politica-Para-Todos/manifestos#42]
https://iniciativaliberal.pt/wp-content/uploads/2022/01/Iniciativa-Liberal-Programa-Eleitoral-2022.pdf

**Comment by fabioatcorreia** [comment]
alguém a pensar fazer a conversão deste programa ou posso contribuir com esta tarefa?

**Comment by marado** [comment]
Força, eu só abri issue para informar do link

-- 
~marado

**Comment by luisiul359** [comment]
> alguém a pensar fazer a conversão deste programa ou posso contribuir com esta tarefa?

Por favor vai ao Discord porque já houve alguma discussão de como acelerar o processo.
